package com.hps.mes.ws.service.m2mdz0100m2041;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-18T22:17:14.882+09:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://M2MDZ0100M2041.service.ws.mes.hps.com/", name = "M2MDZ0100M2041")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface M2MDZ0100M2041 {

    @WebMethod
    public void process(

        @WebParam(partName = "M2MDZ0100M2041Req", name = "M2MDZ0100M2041Req", targetNamespace = "http://M2MDZ0100M2041.service.ws.mes.hps.com/")
        M2MDZ0100M2041Req m2MDZ0100M2041Req
    );
}
